<?php


namespace App\Backoffice\Curriculums\Infrastructure\Persistence\Doctrine;


use App\Backoffice\Curriculums\Domain\CurriculumUuid;
use App\Shared\Domain\Utils;
use App\Shared\Infrastructure\Doctrine\DoctrineCustomType;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;
use function Lambdish\Phunctional\last;

final class CurriculumUuidType extends StringType implements DoctrineCustomType
{
    public function convertToPHPValue($value, AbstractPlatform $platform)
    {

        $uuid = parent::convertToPHPValue($value, $platform);
        return new CurriculumUuid($uuid); // TODO: Change the autogenerated stub
    }


    public static function customTypeName(): string
    {
//        curriculum_uuid
        return Utils::toSnakeCase(str_replace('Type', '', last(explode('\\', static::class))));
    }
}