<?php


namespace App\Backoffice\Users\Infrastructure\Persistence\Doctrine;


use App\Backoffice\Users\Domain\UserEmail;
use App\Backoffice\Users\Domain\UserName;
use App\Backoffice\Users\Domain\UserSurname;
use App\Shared\Domain\Utils;
use App\Shared\Infrastructure\Doctrine\DoctrineCustomType;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\StringType;
use function Lambdish\Phunctional\last;

class UserSurnameType extends StringType implements DoctrineCustomType
{

    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        return parent::convertToDatabaseValue($value, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        $PHPValue = parent::convertToPHPValue($value, $platform);
        return new UserSurname($PHPValue);
    }

    public function getName()
    {
        return Utils::toSnakeCase(str_replace('Type', '', last(explode('\\', static::class))));
    }

    public function requiresSQLCommentHint(AbstractPlatform $platform)
    {
        return true;
    }

    public static function customTypeName(): string
    {
        return Utils::toSnakeCase(str_replace('Type', '', last(explode('\\', static::class))));
    }
}